// ── Weekly digest: what moved on SURGhub this week, from verified figures only ──
//
// Built from the data already on disk — never from an API call: exact enrolment /
// opening / certificate dates (card 2), the hashed account index (sign-ups and logins),
// the course snapshots (card 1), ambassadors, the SURGfund KPI log, and the sync
// health that produced them. The window is the last 7 full days (yesterday back),
// compared with the 7 before. Generated by the background sync on the chosen weekday
// (or by hand); stored device-locally (surgdash_digest, never pushed or exported).
// The optional narrative is written by Claude from the digest's numbers ONLY: the
// figures are handed over as JSON, the prompt forbids any other number, and the text is
// labelled as AI-written so nothing is quoted as a fact without the tiles above it.
Object.assign(window.App, {

    DIGEST_KEY: 'surgdash_digest',
    DIGEST_MODEL: 'claude-opus-4-8',
    DIGEST_TOP: 5,

    // ── dates ──
    _digestDay(d) { const x = new Date(d); x.setHours(0, 0, 0, 0); return x; },
    _digestIso(d) { const x = this._digestDay(d); return x.getFullYear() + '-' + String(x.getMonth() + 1).padStart(2, '0') + '-' + String(x.getDate()).padStart(2, '0'); },
    _digestAddDays(d, n) { const x = this._digestDay(d); x.setDate(x.getDate() + n); return x; },
    // ISO week key (Monday-based), e.g. 2026-W37.
    _digestWeekKey(d) {
        const x = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
        const day = x.getUTCDay() || 7; x.setUTCDate(x.getUTCDate() + 4 - day);
        const y0 = new Date(Date.UTC(x.getUTCFullYear(), 0, 1));
        return x.getUTCFullYear() + '-W' + String(Math.ceil(((x - y0) / 86400000 + 1) / 7)).padStart(2, '0');
    },
    // Last 7 full days (yesterday back) and the 7 before, as inclusive ISO day strings.
    _digestWindow(now) {
        const to = this._digestAddDays(now, -1), from = this._digestAddDays(to, -6);
        const prevTo = this._digestAddDays(from, -1), prevFrom = this._digestAddDays(prevTo, -6);
        return { from: this._digestIso(from), to: this._digestIso(to), prevFrom: this._digestIso(prevFrom), prevTo: this._digestIso(prevTo) };
    },
    _digestIn(day, from, to) { return !!day && day >= from && day <= to; },
    // The ISO day of a stored stamp. Not everything on disk is ISO: KPI-log entries were
    // written with Date.toString() ("Fri Sep 04 2026 16:12:39 GMT+0200 ..."), so slicing
    // the first ten characters gave "Fri Sep 04" — a string that matches no window, which
    // is why SURGfund KPI edits always read zero (found 11 Sep 2026). Parse, then format.
    _digestDayOf(v) {
        const s = String(v == null ? '' : v);
        if (/^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
        if (!s) return '';
        const d = new Date(s);
        return isNaN(d) ? '' : this._digestIso(d);
    },

    // Due on/after the chosen weekday (1 = Monday … 7 = Sunday) once per ISO week — so a
    // Monday the app was closed is caught up on Tuesday, but never twice in a week.
    _digestDue(s, now, stored) {
        const cfg = (s && s.digest) || {}; if (!cfg.enabled) return false;
        now = now || new Date();
        const wd = now.getDay() || 7;
        if (wd < (Number(cfg.day) || 1)) return false;
        return !(stored && stored.week === this._digestWeekKey(now));
    },

    // ── build ──
    async buildWeeklyDigest(opts) {
        opts = opts || {};
        const now = opts.now ? new Date(opts.now) : new Date();
        const w = this._digestWindow(now);
        const rows = (this.ensureCompletionLoaded ? await this.ensureCompletionLoaded() : null) || this._rawCompletion || [];
        const inW = (d) => this._digestIn(d, w.from, w.to), inP = (d) => this._digestIn(d, w.prevFrom, w.prevTo);

        // Course records: the store keeps (mostly) one row per course, stamped with the day
        // that row was last written — so "first seen" says nothing about newness. Provider
        // comes from each course's newest row; "new on the platform" is LearnWorlds' own
        // creation date (CourseCreated) falling in the window (up to today).
        const dates = (this.getAvailableDates ? this.getAvailableDates() : [...new Set((this.data || []).map(r => r.Timestamp))].sort()) || [];
        const latest = dates[dates.length - 1] || '';
        const provOf = {}, provAt = {}, createdOf = {};
        (this.data || []).forEach(r => {
            if (!r || r.IsShell || !r.Course) return;
            const ts = String(r.Timestamp || '');
            if (r.Provider && (!provAt[r.Course] || ts >= provAt[r.Course])) { provOf[r.Course] = r.Provider; provAt[r.Course] = ts; }
            const cd = r.CourseCreated ? String(r.CourseCreated).slice(0, 10) : '';
            if (cd && (!createdOf[r.Course] || cd < createdOf[r.Course])) createdOf[r.Course] = cd;
        });
        const today = this._digestIso(now);
        const newCourses = Object.keys(createdOf).filter(c => createdOf[c] >= w.from && createdOf[c] <= today).sort((a, b) => createdOf[a].localeCompare(createdOf[b]) || a.localeCompare(b));

        // Enrolments, openings, certificates — exact dates from the API rows.
        const cnt = { enrol: 0, enrolPrev: 0, started: 0, startedPrev: 0, certs: 0, certsPrev: 0 };
        const byCourse = {};
        const bump = (course, k) => { const o = byCourse[course] || (byCourse[course] = { course, provider: provOf[course] || '', started: 0, certs: 0, enrol: 0 }); o[k]++; };
        for (const r of rows) {
            if (!r) continue;
            const e = r.enrolled_date || '', s = r.start_date || '', c = r.certificate ? (r.certificate_date || '') : '';
            if (inW(e)) { cnt.enrol++; bump(r.course, 'enrol'); } else if (inP(e)) cnt.enrolPrev++;
            if (inW(s)) { cnt.started++; bump(r.course, 'started'); } else if (inP(s)) cnt.startedPrev++;
            if (inW(c)) { cnt.certs++; bump(r.course, 'certs'); } else if (inP(c)) cnt.certsPrev++;
        }
        const courses = Object.values(byCourse).sort((a, b) => (b.started - a.started) || (b.certs - a.certs) || a.course.localeCompare(b.course)).slice(0, this.DIGEST_TOP);
        const byProv = {};
        Object.values(byCourse).forEach(o => { const p = o.provider || 'Unknown provider'; const q = byProv[p] || (byProv[p] = { provider: p, started: 0, certs: 0, enrol: 0 }); q.started += o.started; q.certs += o.certs; q.enrol += o.enrol; });
        const providers = Object.values(byProv).sort((a, b) => (b.started - a.started) || (b.certs - a.certs)).slice(0, this.DIGEST_TOP);

        // Accounts: sign-ups and active learners from the hashed index (created / last-login day).
        const acc = { newAcc: null, newAccPrev: null, active: null, activePrev: null, listedAt: '' };
        try {
            const idx = this._accountsLoad ? await this._accountsLoad() : null;
            if (idx && idx.byUid) {
                acc.newAcc = 0; acc.newAccPrev = 0; acc.active = 0; acc.activePrev = 0; acc.listedAt = idx.listedAt || '';
                for (const k of Object.keys(idx.byUid)) {
                    const a = idx.byUid[k]; if (!a) continue;
                    if (inW(a.c)) acc.newAcc++; else if (inP(a.c)) acc.newAccPrev++;
                    if (inW(a.l)) acc.active++; else if (inP(a.l)) acc.activePrev++;
                }
            }
        } catch (e) { __swallowed(e, 'digest.accounts'); }

        // Platform totals from the newest learner snapshot.
        const hist = (this.userHistory || []).filter(h => h && h.Timestamp).slice().sort((a, b) => String(a.Timestamp).localeCompare(String(b.Timestamp)));
        const snap = hist[hist.length - 1] || {};
        const platform = { totalUsers: Number(snap.TotalUsers) || 0, totalCertificates: Number(snap.TotalCertificates) || 0, snapshotDate: String(snap.Timestamp || '').slice(0, 10) };

        // Ambassadors: total now; the change comes from the previous digest's snapshot.
        const prev = await this._digestLoad();
        const amb = this.ambassadorData || {};
        const ambassadors = { totalReferrals: Number(amb.TotalReferrals) || 0, prevTotal: prev && prev.snapshot ? Number(prev.snapshot.totalReferrals) || null : null, prevWeek: prev ? prev.week : '' };

        // SURGfund: KPI edits and activities dated this week across projects.
        const surgfund = { kpiEdits: 0, activities: 0, projects: [] };
        try {
            if (window.Projects && Projects.registry) {
                for (const p of Projects.registry.filter(p => p.type === 'generic' && !p.isSample)) {
                    let k = 0, a = 0;
                    try { (await Projects.getKpiLog(p.id) || []).forEach(l => { if (inW(this._digestDayOf(l.timestamp))) k++; }); } catch (e) { __swallowed(e, 'digest.kpilog'); }
                    try { (await Projects.getEvents(p.id) || []).forEach(ev => { if (inW(this._digestDayOf(ev.date))) a++; }); } catch (e) { __swallowed(e, 'digest.events'); }
                    if (k || a) surgfund.projects.push({ name: p.shortName || p.name, kpiEdits: k, activities: a });
                    surgfund.kpiEdits += k; surgfund.activities += a;
                }
            }
        } catch (e) { __swallowed(e, 'digest.surgfund'); }

        // Health: the runs that produced these numbers.
        const health = { bgRuns: 0, bgFailed: 0, lastBgAt: '', enrolLastRun: '', enrolMode: '', sheetsLastSync: '', provenanceFailing: null, dataThrough: latest };
        try {
            const bg = this._bgSettings || (await Storage.getItem('surgdash_bg_sync'));
            if (bg && Array.isArray(bg.history)) {
                const recent = bg.history.filter(r => r && r.at && String(r.at).slice(0, 10) >= w.from);
                health.bgRuns = recent.length; health.bgFailed = recent.filter(r => !r.ok).length; health.lastBgAt = bg.lastRun && bg.lastRun.at || '';
            }
        } catch (e) { __swallowed(e, 'digest.bg'); }
        try { const m = this._enrLoadMeta ? await this._enrLoadMeta() : null; if (m) { health.enrolLastRun = m.lastRun || ''; health.enrolMode = m.lastMode || ''; } } catch (e) { __swallowed(e, 'digest.enr'); }
        try { const as = window.Projects && Projects.getAppSettings ? await Projects.getAppSettings() : null; if (as) health.sheetsLastSync = as.googleSheetsLastSync || ''; } catch (e) { __swallowed(e, 'digest.sheets'); }
        try { const dv = this._deriveVerify || (await Storage.getItem('surghub_derive_verify')); if (dv && Array.isArray(dv.checks)) health.provenanceFailing = dv.checks.filter(c => !c.match && !c.noReceipt).length; } catch (e) { __swallowed(e, 'digest.verify'); }

        return {
            v: 1, week: this._digestWeekKey(now), from: w.from, to: w.to, prevFrom: w.prevFrom, prevTo: w.prevTo, generatedAt: now.toISOString(),
            counts: cnt, accounts: acc, platform, courses, providers, newCourses, ambassadors, surgfund, health,
            snapshot: { totalUsers: platform.totalUsers, totalCertificates: platform.totalCertificates, totalReferrals: ambassadors.totalReferrals },
            narrative: '', narrativeAt: '',
        };
    },

    async _digestLoad() { try { const d = await Storage.getItem(this.DIGEST_KEY); return (d && d.week) ? d : null; } catch (e) { return null; } },
    async _digestStore(d) { this._digest = d; try { await Storage.setItem(this.DIGEST_KEY, d, { internal: true }); } catch (e) { __swallowed(e, 'digest.store'); } },

    async digestGenerateNow() {
        if (this._digestBusy) return;
        this._digestBusy = true;
        try {
            const d = await this.buildWeeklyDigest();
            await this._digestStore(d);
            if (this.showMsg) this.showMsg('Weekly digest generated for ' + d.week + ' (' + d.from + ' → ' + d.to + ').');
        } catch (e) { if (this.showMsg) this.showMsg('Digest failed: ' + (e && e.message || e), true); }
        finally { this._digestBusy = false; if (this.renderView) this.renderView(); }
    },

    // ── text forms ──
    _digestPct(cur, prev) { if (prev == null || cur == null) return ''; if (!prev) return cur ? 'new' : '±0'; const p = Math.round((cur - prev) / prev * 100); return (p > 0 ? '+' : '') + p + '%'; },
    _digestFmtDay(iso) { const d = iso ? new Date(iso + 'T00:00:00') : null; return d && !isNaN(d) ? d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : String(iso || ''); },
    _digestText(d) {
        const n = (v) => this.formatNumber ? this.formatNumber(Number(v) || 0) : String(v);
        const c = d.counts, a = d.accounts || {};
        const L = [];
        L.push('SURGhub weekly digest — ' + d.week + ' (' + this._digestFmtDay(d.from) + ' to ' + this._digestFmtDay(d.to) + ', vs the 7 days before)');
        L.push('');
        L.push('Learning activity');
        L.push('• Courses opened: ' + n(c.started) + ' (' + this._digestPct(c.started, c.startedPrev) + ', prev ' + n(c.startedPrev) + ')');
        L.push('• Enrolments: ' + n(c.enrol) + ' (' + this._digestPct(c.enrol, c.enrolPrev) + ', prev ' + n(c.enrolPrev) + ')');
        L.push('• Certificates issued: ' + n(c.certs) + ' (' + this._digestPct(c.certs, c.certsPrev) + ', prev ' + n(c.certsPrev) + ')');
        if (a.newAcc != null) L.push('• New accounts: ' + n(a.newAcc) + ' (' + this._digestPct(a.newAcc, a.newAccPrev) + ') · learners who logged in: ' + n(a.active) + ' (' + this._digestPct(a.active, a.activePrev) + ')');
        L.push('• Platform total: ' + n(d.platform.totalUsers) + ' accounts, ' + n(d.platform.totalCertificates) + ' certificates (snapshot ' + d.platform.snapshotDate + ')');
        if (d.courses.length) { L.push(''); L.push('Most opened courses this week'); d.courses.forEach((x, i) => L.push((i + 1) + '. ' + x.course + (x.provider ? ' (' + x.provider + ')' : '') + ' — ' + n(x.started) + ' opened, ' + n(x.certs) + ' certificates')); }
        if (d.providers.length) { L.push(''); L.push('Providers'); d.providers.forEach((x, i) => L.push((i + 1) + '. ' + x.provider + ' — ' + n(x.started) + ' opened, ' + n(x.certs) + ' certificates')); }
        if (d.newCourses.length) { L.push(''); L.push('New on the platform (' + d.newCourses.length + '): ' + this._digestListCap(d.newCourses, 8)); }
        L.push('');
        L.push('Ambassadors: ' + n(d.ambassadors.totalReferrals) + ' referrals in total' + (d.ambassadors.prevTotal != null ? ' (' + (d.ambassadors.totalReferrals - d.ambassadors.prevTotal >= 0 ? '+' : '') + n(d.ambassadors.totalReferrals - d.ambassadors.prevTotal) + ' since the ' + d.ambassadors.prevWeek + ' digest)' : ''));
        if (d.surgfund && (d.surgfund.kpiEdits || d.surgfund.activities)) L.push('SURGfund: ' + n(d.surgfund.kpiEdits) + ' KPI edits and ' + n(d.surgfund.activities) + ' activities logged this week' + (d.surgfund.projects.length ? ' (' + d.surgfund.projects.map(p => p.name).join(', ') + ')' : ''));
        const h = d.health || {};
        L.push('');
        L.push('Data health: course data through ' + (h.dataThrough || '—') + ' · enrolment sync ' + (h.enrolLastRun ? String(h.enrolLastRun).slice(0, 10) + ' (' + h.enrolMode + ')' : 'never') + ' · background runs this week ' + h.bgRuns + (h.bgFailed ? ' (' + h.bgFailed + ' with problems)' : ' (all fine)') + ' · Sheets pushed ' + (h.sheetsLastSync ? String(h.sheetsLastSync).slice(0, 10) : 'never') + (h.provenanceFailing != null ? ' · provenance checks failing: ' + h.provenanceFailing : ''));
        if (d.narrative) { L.push(''); L.push('Narrative (AI-written from the figures above)'); L.push(d.narrative); }
        L.push('');
        L.push('Definitions: opened = a course start date in the window; enrolments and certificates by their own dates; new accounts / logins from the account index; percentages compare with the 7 days before. Generated by SURGdash ' + String(d.generatedAt).slice(0, 16).replace('T', ' ') + '.');
        return L.join('\n');
    },
    _digestListCap(list, max) { const l = list || []; return l.length <= max ? l.join(', ') : l.slice(0, max).join(', ') + ' and ' + (l.length - max) + ' more'; },
    // The facts handed to Claude: the digest without prose, nothing else.
    _digestFacts(d) { const f = Object.assign({}, d); delete f.narrative; delete f.narrativeAt; delete f.v; return f; },

    // ── narrative (optional, from the figures only) ──
    async digestWriteNarrative(opts) {
        opts = opts || {};
        const d = this._digest || (await this._digestLoad());
        if (!d) throw new Error('Generate the digest first.');
        const apiKey = this._getAnthropicKey ? await this._getAnthropicKey() : '';
        if (!apiKey) throw new Error('No Claude API key set (Settings → Google Sheets → Claude API key).');
        if (!this._claudeJSON) throw new Error('AI module not loaded.');
        const system = 'You write the weekly digest of SURGhub, the Global Surgery Foundation\'s free surgical-training platform, for the GSF team. You are given the week\'s verified figures as JSON. Write 3 short paragraphs (120–180 words in total): what moved this week versus the week before, the standout courses or providers, and one line on data health. Use ONLY numbers present in the JSON, quoted exactly as given; never estimate, extrapolate or add any figure. Plain, warm, factual English; no headings, no bullet points, no emojis.';
        const schema = { type: 'object', properties: { narrative: { type: 'string' } }, required: ['narrative'], additionalProperties: false };
        const r = await this._claudeJSON(apiKey, system, JSON.stringify(this._digestFacts(d)), schema, 900, { model: this.DIGEST_MODEL });
        d.narrative = String((r && r.narrative) || '').trim(); d.narrativeAt = new Date().toISOString();
        await this._digestStore(d);
        if (!opts.silent && this.renderView) this.renderView();
        return d.narrative;
    },
    async digestWriteNarrativeClick() {
        if (this._digestBusy) return; this._digestBusy = true;
        const el = document.getElementById('digest-narrative'); if (el) el.innerHTML = '<p class="text-sm text-slate-500 italic">Writing…</p>';
        try { await this.digestWriteNarrative(); } catch (e) { if (this.showMsg) this.showMsg('Narrative failed: ' + (e && e.message || e), true); if (this.renderView) this.renderView(); }
        finally { this._digestBusy = false; }
    },
    async digestCopy() {
        const d = this._digest || (await this._digestLoad()); if (!d) return;
        try { await navigator.clipboard.writeText(this._digestText(d)); if (this.showMsg) this.showMsg('Digest copied as text.'); } catch (e) { if (this.showMsg) this.showMsg('Clipboard unavailable: ' + (e && e.message || e), true); }
    },
    async digestEmail() {
        const d = this._digest || (await this._digestLoad()); if (!d) return;
        const subject = 'SURGhub weekly digest ' + d.week + ' (' + this._digestFmtDay(d.from) + ' to ' + this._digestFmtDay(d.to) + ')';
        const href = 'mailto:?subject=' + encodeURIComponent(subject) + '&body=' + encodeURIComponent(this._digestText(d));
        try { if (window.electronAPI && electronAPI.openExternal) electronAPI.openExternal(href); else window.open(href); } catch (e) { if (this.showMsg) this.showMsg('Could not open your mail app: ' + (e && e.message || e), true); }
    },

    // ── Data Sync page panel ──
    _digestPanelHtml() {
        const esc = (t) => this.escapeHtml ? this.escapeHtml(String(t == null ? '' : t)) : String(t);
        const n = (v) => this.formatNumber ? this.formatNumber(Number(v) || 0) : String(v);
        if (this._digest === undefined) { this._digest = null; this._digestLoad().then(d => { this._digest = d; if (this.view === 'upload' && this.renderView) this.renderView(); }); }
        const s = this._bgSettings || {}, cfg = s.digest || { enabled: true, day: 1, narrative: false };
        const days = ['', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
        const d = this._digest;
        const btn = (fn, icon, label, cls) => `<button data-edit-only onclick="App.${fn}()" class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-colors ${cls || 'border border-slate-200 text-slate-600 hover:bg-slate-50'}"><i data-lucide="${icon}" width="13"></i> ${label}</button>`;
        const delta = (cur, prev) => { const p = this._digestPct(cur, prev); const up = cur > (prev || 0), same = cur === prev; return `<span class="text-[11px] font-semibold ${same ? 'text-slate-400' : up ? 'text-emerald-700' : 'text-red-600'}">${esc(p)}</span>`; };
        const tile = (label, cur, prev, note) => `<div class="bg-slate-50 rounded-xl border border-slate-100 p-3"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wide">${label}</p><p class="text-2xl font-bold text-gsf-prussian leading-tight" style="font-family:var(--num)">${n(cur)}</p><p class="text-[11px] text-slate-500">${prev != null ? delta(cur, prev) + ' vs ' + n(prev) : ''}${note ? ' ' + esc(note) : ''}</p></div>`;
        let body;
        if (!d) body = `<p class="text-sm text-slate-500">No digest yet on this device. ${cfg.enabled ? 'The first one is generated by the background sync on ' + days[Number(cfg.day) || 1] + ', or click Generate now.' : 'Enable it, or click Generate now.'}</p>`;
        else {
            const c = d.counts, a = d.accounts || {};
            body = `
                        <p class="text-xs text-slate-500 mb-3">Week ${esc(d.week)} · ${esc(this._digestFmtDay(d.from))} to ${esc(this._digestFmtDay(d.to))}, compared with the 7 days before · generated ${esc(String(d.generatedAt).slice(0, 16).replace('T', ' '))}</p>
                        <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3 mb-4">
                            ${tile('Courses opened', c.started, c.startedPrev)}${tile('Enrolments', c.enrol, c.enrolPrev)}${tile('Certificates', c.certs, c.certsPrev)}
                            ${a.newAcc != null ? tile('New accounts', a.newAcc, a.newAccPrev) + tile('Logged in', a.active, a.activePrev) : ''}
                            ${tile('Accounts total', d.platform.totalUsers, null, d.platform.snapshotDate)}
                        </div>
                        <div class="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-4">
                            <div class="bg-white rounded-xl border overflow-hidden"><div class="bg-slate-50 border-b px-4 py-2 text-xs font-bold text-gsf-prussian">Most opened courses</div>
                                ${d.courses.length ? `<table class="w-full text-xs"><tbody>${d.courses.map(x => `<tr class="border-b border-slate-100 last:border-0"><td class="px-4 py-1.5 text-slate-700 truncate max-w-[260px]" title="${esc(x.course)}">${esc(x.course)}</td><td class="px-2 py-1.5 text-slate-400 truncate max-w-[140px]">${esc(x.provider)}</td><td class="px-2 py-1.5 text-right tabular-nums">${n(x.started)} opened</td><td class="px-4 py-1.5 text-right tabular-nums text-slate-500">${n(x.certs)} certs</td></tr>`).join('')}</tbody></table>` : '<p class="px-4 py-3 text-xs text-slate-400 italic">No courses opened in the window.</p>'}
                            </div>
                            <div class="bg-white rounded-xl border overflow-hidden"><div class="bg-slate-50 border-b px-4 py-2 text-xs font-bold text-gsf-prussian">Providers</div>
                                ${d.providers.length ? `<table class="w-full text-xs"><tbody>${d.providers.map(x => `<tr class="border-b border-slate-100 last:border-0"><td class="px-4 py-1.5 text-slate-700 truncate max-w-[280px]">${esc(x.provider)}</td><td class="px-2 py-1.5 text-right tabular-nums">${n(x.started)} opened</td><td class="px-4 py-1.5 text-right tabular-nums text-slate-500">${n(x.certs)} certs</td></tr>`).join('')}</tbody></table>` : '<p class="px-4 py-3 text-xs text-slate-400 italic">—</p>'}
                            </div>
                        </div>
                        <p class="text-xs text-slate-600 mb-1">${d.newCourses.length ? '<strong>New on the platform (' + d.newCourses.length + '):</strong> ' + esc(this._digestListCap(d.newCourses, 8)) + ' · ' : ''}<strong>Ambassadors:</strong> ${n(d.ambassadors.totalReferrals)} referrals${d.ambassadors.prevTotal != null ? ' (' + (d.ambassadors.totalReferrals - d.ambassadors.prevTotal >= 0 ? '+' : '') + n(d.ambassadors.totalReferrals - d.ambassadors.prevTotal) + ' since ' + esc(d.ambassadors.prevWeek) + ')' : ''}${d.surgfund && (d.surgfund.kpiEdits || d.surgfund.activities) ? ' · <strong>SURGfund:</strong> ' + n(d.surgfund.kpiEdits) + ' KPI edits, ' + n(d.surgfund.activities) + ' activities' : ''}</p>
                        <p class="text-[11px] text-slate-400 mb-3">Data health: course data through ${esc(d.health.dataThrough || '—')} · enrolment sync ${esc(d.health.enrolLastRun ? String(d.health.enrolLastRun).slice(0, 10) : 'never')} · background runs this week ${d.health.bgRuns}${d.health.bgFailed ? ' (' + d.health.bgFailed + ' with problems)' : ''} · Sheets pushed ${esc(d.health.sheetsLastSync ? String(d.health.sheetsLastSync).slice(0, 10) : 'never')}${d.health.provenanceFailing != null ? ' · provenance checks failing: ' + d.health.provenanceFailing : ''}</p>
                        <div id="digest-narrative" class="mb-2">${d.narrative ? `<div class="bg-sky-50 border border-sky-100 rounded-xl p-4 text-sm text-slate-700 leading-relaxed whitespace-pre-line">${esc(d.narrative)}</div><p class="text-[10px] text-slate-400 mt-1">AI-written from the figures above only (${esc(String(d.narrativeAt).slice(0, 16).replace('T', ' '))}). Check against the tiles before quoting.</p>` : ''}</div>`;
        }
        return `
                    <!-- ── Weekly digest ── -->
                    <div class="bg-white border border-slate-200 rounded-2xl p-5 mb-4 shadow-sm">
                        <div class="flex flex-wrap items-start justify-between gap-4 mb-3">
                            <div class="min-w-0">
                                <div class="flex flex-wrap items-center gap-2 mb-1">
                                    <i data-lucide="newspaper" width="18" class="text-gsf-prussian"></i>
                                    <h2 class="text-lg font-bold text-gsf-prussian">Weekly digest</h2>
                                </div>
                                <p class="text-sm text-slate-600 max-w-3xl">What moved in the last seven days, from the verified figures on this device. Generated after the background sync on the chosen day; copy it or open it in your mail app to send round.</p>
                            </div>
                            <div class="flex flex-col items-end gap-2 shrink-0 text-xs">
                                <label class="inline-flex items-center gap-2 font-bold text-slate-700 cursor-pointer"><input type="checkbox" data-edit-only ${cfg.enabled ? 'checked' : ''} onchange="App._bgSet({ digest: { enabled: this.checked } })"> Generate every week</label>
                                <label class="inline-flex items-center gap-2 text-slate-600">On <select data-edit-only onchange="App._bgSet({ digest: { day: Number(this.value) } })" class="border rounded px-1.5 py-0.5 text-xs">${days.map((nm, i) => i ? `<option value="${i}" ${Number(cfg.day) === i ? 'selected' : ''}>${nm}</option>` : '').join('')}</select></label>
                                <label class="inline-flex items-center gap-2 text-slate-600 cursor-pointer" title="Uses your Claude API key; the text is written from the digest's numbers only."><input type="checkbox" data-edit-only ${cfg.narrative ? 'checked' : ''} onchange="App._bgSet({ digest: { narrative: this.checked } })"> Add the AI narrative automatically</label>
                                <div class="flex flex-wrap items-center gap-2 justify-end">
                                    ${btn('digestGenerateNow', 'refresh-cw', d ? 'Regenerate' : 'Generate now', 'bg-gsf-boston text-white hover:bg-gsf-prussian')}
                                    ${d ? btn('digestWriteNarrativeClick', 'sparkles', d.narrative ? 'Rewrite narrative' : 'Write narrative') : ''}
                                    ${d ? btn('digestCopy', 'copy', 'Copy text') : ''}
                                    ${d ? btn('digestEmail', 'mail', 'Email…') : ''}
                                </div>
                            </div>
                        </div>
                        ${body}
                    </div>
`;
    },
});
